quarkus:
  datasource:
    db-kind: postgresql
    username: hsm
    password: hsm
    jdbc:
      url: jdbc:postgresql://localhost:5432/hsm_db
  hibernate-orm:
    log:
      sql: true
    statistics: true
    database:
      generation: drop-and-create
    