version: "2.3"

services:
  application:
    build:
      context: ../../..
      dockerfile: src/main/docker/Dockerfile.native
    image: karl/hsm-api-native:latest
    mem_limit: 128m
    environment:
      - QUARKUS_DATASOURCE_JDBC_URL=jdbc:postgresql://database:5432/application_db
      - QUARKUS_DATASOURCE_USERNAME=application
      - QUARKUS_DATASOURCE_PASSWORD=application
    ports:
      - "8080:8080"
    depends_on:
      database:
        condition: service_healthy
    networks:
      - application_network

  database:
    image: "postgres:14"
    mem_limit: 128m
    environment:
      - POSTGRES_DB=application_db
      - POSTGRES_USER=application
      - POSTGRES_PASSWORD=application
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U application_db"]
      interval: 5s
      timeout: 5s
      retries: 6
    ports:
      - "5432:5432"
    networks:
      - application_network

networks:
  application_network:
    driver: bridge