GET http://localhost:8080/keys

###
GET http://localhost:8080/keys/1

###
POST http://localhost:8080/keys
content-type: application/json

{
    "name": "key-1"
}

###

POST http://localhost:8080/keys
content-type: application/json

{
    "algorithm": "EC_P256"
}

###
POST http://localhost:8080/keys
content-type: application/json

{
    "algorithm": "EC_ED25519"
}

###
POST http://localhost:8080/keys
content-type: application/json

{
    "algorithm": "EC_ED448"
}

###

POST http://localhost:8080/keys
content-type: application/json

{
    "algorithm": "RSA_PSS_2048"
}

###

POST http://localhost:8080/keys/1/sign
content-type: application/json

abcd

###

POST http://localhost:8080/keys/1/sign
content-type: application/octet-stream

abcd

###

POST http://localhost:8080/keys/3/sign
content-type: application/octet-stream

abcd

###

DELETE http://localhost:8080/keys/1

###
GET http://localhost:8080/info/key-algorithms
###
GET http://localhost:9000/q/health
###
GET http://localhost:9000/q/health/live
###
GET http://localhost:9000/q/health/ready
###
