GET http://localhost:8080/keys

###
GET http://localhost:8080/keys/1

###

POST http://localhost:8080/keys
content-type: application/json

{
    "algorithm": "EC_P256"
}

###

POST http://localhost:8080/keys
content-type: application/json

{
    "algorithm": "RSA_PSS_2048"
}

###

POST http://localhost:8080/keys
content-type: application/json

{
    "algorithm": "RSA_PSS_2048",
    "createdAt": "xyz"
}

###

POST http://localhost:8080/keys/1/sign
content-type: application/json

{
    "algorithm": "EdDSA" 
}

###

POST http://localhost:8080/keys
content-type: application/json

{
    "algorithm": "RSA_PSS_2048"
}

###

POST http://localhost:8080/keys/1/sign
content-type: application/json

abcd

###

POST http://localhost:8080/keys/1/sign
content-type: application/octet-stream

abcd

###

POST http://localhost:8080/keys/2/sign
content-type: application/json

abcd