GET http://localhost:8080/keys HTTP/1.1

###

GET http://localhost:8080/keys/1

###

POST http://localhost:8080/keys HTTP/1.1
content-type: application/json

{
    "algorithm": "EC_P256"
}

###

POST http://localhost:8080/keys HTTP/1.1
content-type: application/json

{
    "algorithm": "RSA_PSS_2048"
}

###

GET http://localhost:8080/keys/47

###


DELETE http://localhost:8080/keys/47 HTTP/1.1

###

POST http://localhost:8080/keys/53 HTTP/1.1
content-type: application/json

{
    "algorithm": "EC_P256"
}

###

GET http://localhost:8080/keys/53

###

POST http://localhost:8080/keys/13 HTTP/1.1
content-type: application/json

###

GET http://localhost:8080/keys/456

###

POST http://localhost:8080/keys/1/sign HTTP/1.1
content-type: application/json

{
    "algorithm": "EdDSA" 
}

###

POST http://localhost:8080/keys HTTP/1.1
content-type: application/json

{
    "algorithm": "RSA_PSS_2048"
}

###

POST http://localhost:8080/keys/1/sign HTTP/1.1
content-type: application/json

abcd